package cn.mine.minestars.core.tavern.macro

data class TemplateFieldBag(
    val assistantName: String,
    val userName: String,
    val userDescription: String,
    val characterDescription: String,
    val characterPersonality: String,
    val characterScenario: String,
    val characterFirstMessage: String,
    val characterSystemPrompt: String,
    val postHistoryInstructions: String,
    val creatorNotes: String,
    val messageExamples: String,
    val characterVersion: String,
    val depthPrompt: String,
    val historyText: String
) {
    fun toMap(): Map<String, String> {
        return mapOf(
            "char" to assistantName,
            "character" to assistantName,
            "assistant" to assistantName,
            "name2" to assistantName,
            "charifnotgroup" to assistantName,
            "user" to userName,
            "username" to userName,
            "user_name" to userName,
            "name1" to userName,
            "persona" to userDescription,
            "personadescription" to userDescription,
            "personadescriptionraw" to userDescription,
            "user_description" to userDescription,
            "description" to characterDescription,
            "chardescription" to characterDescription,
            "personality" to characterPersonality,
            "scenario" to characterScenario,
            "first_mes" to characterFirstMessage,
            "first_message" to characterFirstMessage,
            "firstmessage" to characterFirstMessage,
            "greeting" to characterFirstMessage,
            "mesexamples" to messageExamples,
            "mesexamplesraw" to messageExamples,
            "mes_example" to messageExamples,
            "dialogueexamples" to messageExamples,
            "charprompt" to characterSystemPrompt,
            "main" to characterSystemPrompt,
            "system" to characterSystemPrompt,
            "char_prompt" to characterSystemPrompt,
            "system_prompt" to characterSystemPrompt,
            "posthistoryinstructions" to postHistoryInstructions,
            "charinstruction" to postHistoryInstructions,
            "charjailbreak" to postHistoryInstructions,
            "jailbreak" to postHistoryInstructions,
            "creatornotes" to creatorNotes,
            "charversion" to characterVersion,
            "char_version" to characterVersion,
            "depthprompt" to depthPrompt,
            "chardepthprompt" to depthPrompt,
            "chat_history" to historyText,
            "chathistory" to historyText,
            "history" to historyText
        )
    }
}
