// https://developer.android.com/jetpack/compose/performance/stability/fix#configuration-file

// Kotlin Immutable Collections
kotlinx.collections.immutable.*

kotlin.uuid.*
kotlin.time.*

// Java Time
java.time.*

cn.mine.minestars.data.model.Conversation
cn.mine.minestars.data.model.MessageNode
cn.mine.ai.ui.UIMessage
cn.mine.ai.ui.UIMessageChoice
cn.mine.ai.ui.MessageChunk
cn.mine.ai.ui.UIMessageAnnotation
cn.mine.ai.ui.ToolApprovalState
cn.mine.ai.core.TokenUsage